### PR TITLE
modernized dependencies

### PR DESCRIPTION
**Pull request by philiplb**
So this works with symfony 4.

### CODE REVIEW

**Comment by philiplb** [comment]
@varspool any chance this could get merged?

**Comment by DanielSiepmann** [comment]
@philiplb I think this pull request has better chances if the build does not fail.

Currently the issue is that `.travis.yml` was not updated to run with corresponding PHP versions. Also the new dependencies raise the required PHP version up to 7.1 as a minimum. 5.6 is still supported on some operating systems. I'm not sure whether the author likes this breaking chance.

Did you try to only allow the installation of you versions in addition? composer will by itself require the newest possible version. If you add the required versions in addition and update the `.travis.yml` you might get what you want, without being breaking.

**Comment by philiplb** [comment]
Good point, will update to the needed version(s).

**Comment by sabbelasichon** [comment]
@philiplb I did a new pull request #22 with the same intention. If you like you can comment on it. Would  like to merge the PR as soon as possible.

**Pull request closed without merging**
